### PR TITLE
add confirmation ID generator, fix server.cpp

### PR DESCRIPTION
**Pull request by WitherOrNot**
Adds a linux port of xp_activate32 for command line and also fixes a build error for server.cpp

### CODE REVIEW

**Comment by Neo-Desktop** [comment]
the rest of this looks great though!

**Comment by CONIGUERO** [comment]
> Adds a linux port of xp_activate32 for command line and also fixes a build error for server.cpp

Doesn't seem to work on macOS

**Comment by WitherOrNot** [comment]
What is the error?

**Comment by CONIGUERO** [comment]
> What is the error?

```
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/crc32intrin.h:73:10: error: use of undeclared identifier '__builtin_ia32_crc32si'
  return __builtin_ia32_crc32si(__C, __D);
         ^
```
[...]

```
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"
 ^
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:37:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
    __builtin_ia32_emms();
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/math.h:670:12: note: '__builtin_isless' declared here
    return isless(__lcpp_x, __lcpp_y);
           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/math.h:545:22: note: expanded from macro 'isless'
#define isless(x, y) __builtin_isless((x),(y))
                     ^
```

**Comment by WitherOrNot** [comment]
Are you building on an ARM mac?

**Comment by CONIGUERO** [comment]
> Are you building on an ARM mac?

Yep, M1

**Comment by WitherOrNot** [comment]
I just pushed a new commit, see if this works.

**Comment by CONIGUERO** [comment]
> I just pushed a new commit, see if this works.

Confirmed built and working! Thank you. I will wait for the rest of the team's opinion before merging

**Review by Neo-Desktop — APPROVED** [review]
Approved

**Pull request merged**
